### PR TITLE
Feature: User interface

### PR DESCRIPTION
**Pull request by moinkhanif**
This feature requests for user input and collects it.
The logic shall be added in the succeeding PL

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Require Changes🛑
# 🙋‍♂️ Team,
You have done a good job so far🙂, here are a few things we have to do in this milestone to the project approved🙂.
In this milestone you are required to:
* [x] main.rb uses puts/print and get.chomp commands. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/main_rb.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).
Use ```get.chomp``` to read input from the user, like the player name, selected position etc...
* [x] Set basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
-  `[REQUIRED]` game tells which player turn it is
-  `[REQUIRED]` game asks the player to select from available moves
-  `[REQUIRED]` game informs the player if the selected move is invalid
-  `[REQUIRED]` game displays board after the player move
-  `[REQUIRED]` game informs the player if the selected move is a winning move
-  `[REQUIRED]` game informs the player if the selected move is a draw move
-  `[REQUIRED]` game repeats all actions for the next player's move
* [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [x]  **[OPTIONAL]** game ask players for their names
> note: This not to say everything has to be working perfectly, but these steps will form the basis for the next milestone and it is imperative that we see that you have thought of the ingredient that will make your project. For example, at this stage, you can declare a winner or draw randomly after a number turn, that way. We have to see players taking turns and selecting positions. refer to the game flow requirement in my second recommendation.
## That is it, kindly make these changes and submit the project for review🙂.
#### Happy coding💻
Addo

**Comment by Anna-Myzukina** [comment]
## Hi team ! Very nice project! :wave: 

# Status: [changes required]

 It looks great and is nicely coming into place, but we need to be able to play with the basic flow.

*The final point of this milestone is to make sure that you thought about all the actions needed to play Tic Tac Toe from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)
Basic game flow is prepared: 
screen
- [x] [REQUIRED] game informs the player if the selected move is `invalid` (as I can see your game informs if move is valid)
- [x] [REQUIRED] game informs the player if the selected move is a `draw` move

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Comment by kirokoNjenga** [comment]
image
- According to the requirement of the Milestone 2, I believe we have achieved

**Comment by kirokoNjenga** [comment]
image
- on the requirement with the previous TSC, everything is three as dedicated above 
-Can also check on the code

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your did a great job, approved :+1:  
* Before you merge this pull request, kindly change `full` to `draw`. It suits game rules more then `full`.

Then go on and merge to develop.
_Goodluck in your next milestone_ *Happy coding*

**Pull request merged**
