### PR TITLE
Feature : Setting up require file for the Tic_Tac_Toe project

### PR DESCRIPTION
**Pull request by moinkhanif**
As per the requirement for this milestone, we set up the following files:

- lib - for the game logic
- bin with executable main.rb file
- setup main.rb file to Display "Hello World!"

### CODE REVIEW

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi team, 👋 

### Great job thus far! 🙌 Code looks good, just one suggestion to wrap this up. 👇 

- [ ] Set up linter properly. It should appear as shown below:
Screenshot 2020-03-23 at 19 42 45

**Kindly submit another code review request once this has been fixed.** Happy coding!_ 🎉

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Good job adding linter files :+1: 
One more thing is incorrect:
* [ ] Rubocop file should not be empty. [Here](https://github.com/microverseinc/linters-config/tree/master/ruby) are configurations for linters for ruby projects.

Consider in future giving repository feature branches descriptive names, like for this milestone branch name could be `project_setup`
### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by moinkhanif** [comment]
I truly apologize for the inconvenience. I will make sure to check all the basic files before proceeding with the PL. Thank you for correcting me. 👍 Files are now fixed

**Comment by Anna-Myzukina** [comment]
# Status: [APPROVED]


### Go ahead and merge to master.

* Just one thing, you in your project you have two files .strickler.yml , please delete one of them. 
#### Goodluck in your next project Happy coding <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
